### ISSUE TITLE
User can see and edit general information about lead

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#1]
## Criteria
- [x] User can see lead stage
- [x] User can see info about owner
- [x] After click on name should open popup for edit
- [x] user can accept or dismiss changes in popup
- [x] lead name cannot be empty
- [x] user see validation error for empty name
## Tasks
- [x] Create popover for edit; (4)
- [x] Create edit lead header component (4)
