### ISSUE TITLE
User can see amount of activities on activities link in header.

### ISSUE THREAD

**Issue by denyskom** [softwareplanet/leadboard#102]
## Criteria
- [ ] user can see badge with amount of activities (scheduled for today and overdue) on activities link, in header, if they are present.
![fd6907c0_2018 27 08](https://user-images.githubusercontent.com/40685906/44650024-37e70e00-a9ee-11e8-9e6d-b0de2ab72fad.png)
## Tasks
- [ ] add badge to activity link
- [ ] add method that counts amount of overdue and today's activities
- [ ] add render logic depending on amount of activities
- [ ] add tests
