### ISSUE TITLE
User can see all people on people page (10)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#103]
## Criteria
- [x] User can see contacts dropdown on leadbord
- [x] User can see table with all organisations on people page
- [x] Table should has styles: 
![image](https://user-images.githubusercontent.com/40685592/45609709-ba00aa80-ba61-11e8-910b-3a5c400fcfe3.png)
- [x] User can see info from custom fields for peoples in the table
- [x] User can see organization connected with this person
- [x] User can see amount of open and closed leads, owner and next activity date
![image](https://user-images.githubusercontent.com/40685592/45612030-4a42ed80-ba6a-11e8-90b4-af1e76ad5bcd.png)

## Tasks
- [x] Add styles to table (5)
- [x] Disable edit possibility of table (1)
- [x] Make table reusable (1)
- [ ] Add tests (2)
- [x] Click on a row will open the contact page (1)
