### ISSUE TITLE
User can add new contact on people page (14.5/9)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#104]
## Criteria 
- [x] User can see add person button on people page
![image](https://user-images.githubusercontent.com/40685592/45610664-6d1ed300-ba65-11e8-80e9-219d6e57df45.png)

- [x] User can add new contact from people page
![image](https://user-images.githubusercontent.com/40685592/45611006-a73ca480-ba66-11e8-88a1-45a6ef2c607e.png)

## Tasks
- [x] Add new person modal layout (5)
![image](https://user-images.githubusercontent.com/40685592/45610996-9b50e280-ba66-11e8-96ad-548bede067e5.png)
- [x] Name cannot be empty (1)
![image](https://user-images.githubusercontent.com/40685592/45611293-980a2680-ba67-11e8-8f8f-e1876a5d267e.png)
- [x] Add organization autocomplete to modal(2.5)
![image](https://user-images.githubusercontent.com/40685592/45610902-4319e080-ba66-11e8-9f25-93014507911d.png)
- [x] Create backend for adding new contact (3)
- [x] Add backend tests (1)
- [x] Add actions/reducers (1)
- [x] Add frontend tests (1)

**Comment by valentyntu** [comment]
Done in #260
