### ISSUE TITLE
User can add, edit custom fields of organization and contact on lead edit page (19)

### ISSUE THREAD

**Issue by denyskom** [softwareplanet/leadboard#106]
## Criteria
- [ ] Edit custom field card and add custom field card should be reusable component
![dbfd9f56_2018 10 09](https://user-images.githubusercontent.com/40685592/45298159-54b43300-b510-11e8-948e-22beeff8504c.png)

![b81aed1f_2018 10 09](https://user-images.githubusercontent.com/40685592/45283561-e7d87300-b4e6-11e8-991f-3182200515c9.png)

## Tasks
- [ ] API for create and edit custom field - 8
- [ ] Make component layout with styles  - 7
- [ ] Add tests - 4
