### ISSUE TITLE
User can set activity as done on lead page (5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#112]
## Criteria
- [x] Click on radio button will move activity to history and check radio button
![e08adcce_2018 31 08](https://user-images.githubusercontent.com/40685592/44902330-5d3b8b00-ad12-11e8-8ee1-b46615bd3a6b.png)
![2f3d54a7_2018 31 08](https://user-images.githubusercontent.com/40685592/44902369-7fcda400-ad12-11e8-9052-7ff270fca772.png)

## Tasks
- [x] add radio button click handler that will trigger patch and update activity done to true - 1h
- [x] conditional render done and undone activities  - 3h
- [ ] add tests - 2h
