### ISSUE TITLE
User can add organization and person to lead if it wasn't set on creation (16/23)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#116]
## Criteria
- [x] If organization was not set on creating a lead user will see the following card
![2d74296a_2018 27 08](https://user-images.githubusercontent.com/40685314/44661352-177d7a80-aa13-11e8-8462-e3b9413fb589.png)
- [x] If it is a contact card, it should have word "person" everywhere instead of "organization"
- [x] User can click on "+ Link and organization" and see the next modal window
![f861063f_2018 27 08](https://user-images.githubusercontent.com/40685314/44661421-4d226380-aa13-11e8-8583-61bf763ddd41.png)
- [x] If it is a link contact modal, it should have word "person" everywhere instead of "organization"
- [x] User will receive suggestions when typing and will be able to choose form the list of existing organizations/contacts
- [x] User can submit linking an organization by clicking "Link this organization" button, same for contact but with sign "Link this contact"

## Tasks
- [x] Create view for empty card (4)
- [x] Create modal window (2)
- [x] Add conditional auto-complete (4)
- [x] Add action and reducer for linking organization to lead (2)
- [x] Add action and reducer for linking person to lead (2)
- [x] Change backend contact patch to create new organization or contact (2)
Reuse auto-complete from adding lead
