### ISSUE TITLE
Separate organization and contact in lead's model (4.5/6.5)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#117]
## Tasks 
- [x] Change backend to create contact and organization separately and put ids in lead on its creation (3)
- [x] Change card view on leadboard (0.5)
- [x] Change edit view (0.5)
- [x] Change leadReducer (0.5)
