### ISSUE TITLE
User can edit activity (11/13)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#118]
## Criteria
- [x] user can see modal window for editing
- [x] user can edit type of activity
- [x] user can edit time and duration of activity
- [x] user can edit activity subject

## Tasks
- [x] create reusable modal component (5)
- [x] add validation to activity patch (1)
- [x] create tests (2)
