### ISSUE TITLE
User can delete activity (11/4)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#119]
## Criteria
- [x] User can see menu button in the top right corner of activity card on edit lead page
![790da7a2_2018 03 09](https://user-images.githubusercontent.com/40685314/44971365-f7434380-af5d-11e8-85a6-9ccaea73fac8.png)
- [x] On clicking edit button user can see menu in popover which contains "Delete"
![0c17b1c8_2018 03 09](https://user-images.githubusercontent.com/40685314/44971498-746eb880-af5e-11e8-998d-08bac298061f.png)
- [x] On choosing "Delete" user will see confirmation dialogue
![7fac35ad_2018 03 09](https://user-images.githubusercontent.com/40685314/44971540-a6801a80-af5e-11e8-99cd-1a0cf1d20134.png)
- [x] If user chooses OK in confirmation dialogue, an activity disappears from activities
## Tasks
- [x] Add button to activity card layout - (1)
- [x] Add popover on on clicking button - (1)
- [x] Add "Delete" item to popover and write delete func - (1)
- [x] Add delete activity backend - (2)
- [x] Add actions and reducers for deleting activity - (1.5)
- [x] Bind delete func to delete activity action (0.5)
- [x] Add tests (2)
