### ISSUE TITLE
User can see all planned activities in calendar when creating new activity (12)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#137]
## Criteria 
- [ ] On adding activity user can see calendar on the left of activity form
- [ ] Calendar shows current date by default
- [ ] User can change date, using arrow buttons on the top right corner
- [ ] Calendar displays all planned activities for the selected date over against their planned time
- [ ] The size of activity depends on its duration
![f5452d13_2018 30 08](https://user-images.githubusercontent.com/40685314/44848679-61a76b80-ac60-11e8-8e89-9920a1501143.png)
## Tasks
- [ ] Discover how to use [this](http://intljusticemission.github.io/react-big-calendar/examples/index.html) component and add it to add activity view (2)
- [ ] Style calendar to make it as close as possible to the provided example (4)
- [ ] Add displaying planned activities on loading and updating them on date change (4)
- [ ] Add tests (2)
