### ISSUE TITLE
User can see new activity positioned on calendar before creating

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#139]
## Criteria
- [ ] Changing time, date and duration of new activity will make its card to change its size and position on calendar
- [ ] User will see start and finish time of the activity
![77802686_2018 30 08](https://user-images.githubusercontent.com/40685314/44851109-ecd82f80-ac67-11e8-86ee-3aaea005afc3.png)
- [ ] User can drag and drop new activity to change its start time
## Tasks
- [ ] Add drag and drop handler that will update start time on activity form
- [ ] Disable drag and drop for all activities excluding the new one
