### ISSUE TITLE
User can select stage of lead

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#14]
## Criteria
- [x] Passed stages are green
- [x] Not passed stages are gray
- [x] Every stage has hover with stage name
- [x] If lead is lost passed stages are red
- [x] hover with stage name

## Tasks
- [x] API request handler for GET lead
- [x] API request handler for PATCH lead (1.5)
- [x] Create arrow stage component
