### ISSUE TITLE
User can add an activity to lead (12)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#15]
## Criteria
- [x] Add activity tab
![image](https://user-images.githubusercontent.com/40685592/44665514-c2476600-aa1e-11e8-8c1a-a3353741527f.png)

- [x] User can choose type of activity
![image](https://user-images.githubusercontent.com/40685592/44650665-eb9ccd80-a9ef-11e8-90ff-02121392d4d3.png)

- [x] User can specify its name
![image](https://user-images.githubusercontent.com/40685592/44650680-f6576280-a9ef-11e8-8d54-ef38fd7d9283.png)

- [x] Name set to type name by default (placeholder and value)
![image](https://user-images.githubusercontent.com/40685592/44650847-6960d900-a9f0-11e8-81c3-c627ba2cb294.png)

- [x] User choose date, time and duration
![image](https://user-images.githubusercontent.com/40685592/44650863-7251aa80-a9f0-11e8-89b1-0946e3bfcaee.png)

## Tasks
- [x]  Create rest API for adding new Activity - 3h / 3:45 + 2 h (after review and discussion)
- [x] Add activity tab - 0.5h / 5h
- [x] Make basic component's layout - 3h
- [x] Make styles - 3h (layout and styles 18h, datepicker 5h)
- [x] Make separate button for each activity type - 1h (2h)
- [x] Add action/reduser - 2h / 3h

- [x] Add tests - 3h (frontend 2h, backend 3h)
