### ISSUE TITLE
User can filter leads on dashboard (8)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#160]
## Criteria
- [x] User can see filter popover on leadboard 
- [x] User can get  (won-, lost-, all-) leads
- [x] User see all leads by default filter option "all open leads"

## Tasks
- [x] Add filter button with popover on leadbord (3)
![a6a79e6b_2018 03 09](https://user-images.githubusercontent.com/40685761/44973215-7b002e80-af64-11e8-9dfd-8226407d6926.png)
- [x] Change current get api on get with optional filter field (2)
- [x] Write tests (1.5)
