### ISSUE TITLE
Generify populates for lead routes (2/2.5)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#161]
## Tasks
- [x] Move all populate params to arrays (0.5)
- [x] Combine all types of population params arrays into objects (0.5)
- [x] Ensure everything is working as before and add/expand tests (1)
