### ISSUE TITLE
User can set lead as won or lost  (8/1.5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#18]
## Criteria
- [x] User can see 'won' or 'lost' buttons on edit lead page 
## Tasks
- [x] Add new field to Lead DB model which indicates current lead's status (won, lost, in progress) (1/0)
- [x] Add buttons to current edit lead header component (3/0.5)
![ea7e69c2_2018 27 08](https://user-images.githubusercontent.com/40685761/44645446-50502c00-a9e0-11e8-9114-40c9379e80a0.png)
- [x] API request handler for PATCH lead (1/0)
- [x] API request handler for GET lead (1/0)
- [x] Create test (2/1)
