### ISSUE TITLE
User can see a hint of names after entered organization name in add lead modal (6)

### ISSUE THREAD

**Issue by NazarPo** [softwareplanet/leadboard#19]
## Criteria
- [x] each time user entered a new symbol he can see a hint of organizations names if those exists
- [x] if there no coincidence user can see a hint with message that it will be new organization
- [x] if user entered one symbol hints don't appear
- [x] if entered name is new user can see a label "NEW"
- [x] before creating new lead, if lead title is empty, but title placeholder is not so, lead will be created with title as placeholder text

## Tasks 
- [x] add rendering unordered list of hints 1h
- [x] add api request handler for GET domain 0.5h
- [x] add label with message "NEW" 0.5h
- [x] add capability of choosing organization name from list of hints 2h
- [x] create tests 2h

## Tests
_todo_
