### ISSUE TITLE
Autohrized user can see dropdown on the navbar (5)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#197]
## Criteria
- [ ] After login user can see dropdown with his name and domain name
![7a97aafd_2018 10 09](https://user-images.githubusercontent.com/40685314/45280953-ffabf900-b4de-11e8-90d9-e69fe30be417.png)
- [ ] On clicking it user will see the list of quick actions
![c5502f4c_2018 10 09](https://user-images.githubusercontent.com/40685314/45281016-2c601080-b4df-11e8-8490-47aec7d7f060.png)
- [ ] The list contains log out and link to settings page
## Tasks
- [ ] Create dropdown inside navbar(with proper styles for it and its items) - 2
- [ ] Move exisitng card with user info inside dropdown - 1
- [ ] Move log out to dropdown items - 0.5
- [ ] Add link to settings page - 0.5
- [ ] Fix tests - 1
