### ISSUE TITLE
User can search items using search bar

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#198]
## Creteria
- [x] User can see search input in navigation bar
![3ba33963_2018 10 09](https://user-images.githubusercontent.com/40685761/45281924-07b96800-b4e2-11e8-8d1c-e55863296d72.png)
- [x] User can see list of suggestions after input 2 letters
![87ab87d3_2018 10 09](https://user-images.githubusercontent.com/40685761/45282018-6383f100-b4e2-11e8-80e8-87402f28643a.png)
- [x] User can see tabs with the types of suggestions (all, only leads)
- [x] User can choose any type of suggestion
- [x] User can choose one suggestion and after that he will be redirected to the page with suggestion info

## Tasks
- [x] Create search input in navigation bar (0.5h)
- [x] Add search component (2h)
- [x] Add different types of suggestions (2h)
- [x] Add capability to switch between types of suggestions(2h)
- [x] Add GET request for all leads in domain populating organizations and contacts of lead(1h)
- [x] Add reducer and action (2h)
- [x] Add CSS styles for input (2h)
- [x] Add CSS styles for list of suggestions(3h)
- [x] Tests (3h)
