### ISSUE TITLE
User can select stage while creating new lead

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#2]
## Criteria
- [x] pick a stage from stage-progress
- [x] previous stages fills up with green representing that they are passed
![bc45d8a7_2018 16 08](https://user-images.githubusercontent.com/40685592/44207199-fd1ae580-a164-11e8-8af0-5cce1193b195.jpg)
- [x] a tooltip with stage's name appears at the bottom of the stage
![2892287d_2018 16 08](https://user-images.githubusercontent.com/40685592/44207280-479c6200-a165-11e8-9dc1-5e2af7389e7a.jpg)

## Tasks
- [x] create group of checkbox stages of current leadboard
- [x] on stage click add selected stage to request params
- [x] styles of checkboxes
- [x] passed stages --green, others --grey
- [x] add tests 

## Tests
- ~~stages quantity comes via props~~
- ~~default class "active" for first stage~~
- ~~class "active" for selected stage (on click)~~
- ~~click on stage trigger function that select the stage~~
