### ISSUE TITLE
User can see notification on lead card (12)

### ISSUE THREAD

**Issue by denyskom** [softwareplanet/leadboard#20]
## Criteria
- [x] user can see special icon (green) on leads that have activity for today on leadboard 
![image](https://user-images.githubusercontent.com/40685592/44647377-90b2a880-a9e6-11e8-9392-73dd8fb330a6.png)

- [x] user can see special icon (red) on leads that have overdue activity
![image](https://user-images.githubusercontent.com/40685592/44647401-a3c57880-a9e6-11e8-985f-466be3bfe89f.png)

- [x] user can see special icon (gray) on leads that have scheduled activities
![image](https://user-images.githubusercontent.com/40685592/44647529-f737c680-a9e6-11e8-85fb-3cacdee2a009.png)

- [x] when new lead is added to leadboard a warning icon appears on it
![warning icon](https://user-images.githubusercontent.com/40685314/44153250-644e7bf0-a0b0-11e8-9d0a-3e3ed14df9f3.png)

- [x] when all activities are done the warning icon also appears

## Tasks
- [x] find suitable icons - 1h
- [x] extend lead layout with icon placeholder - 1h
- [x] create function that checks if lead has planned activities - 1h
- [x] add icon rendering on the lead that depends on checking function - 0.5h
- [x] add tests - 1.5h
