### ISSUE TITLE
User can see organization and contact custom fields on lead edit page (25)

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#200]
## Criteria
- [x] User can click on the customize fields button
![9f5b2557_2018 10 09](https://user-images.githubusercontent.com/40685592/45281804-a72a2b00-b4e1-11e8-849e-30d11444e12a.png)
- [x] Choose customize fields from poopover
![6757de2a_2018 10 09](https://user-images.githubusercontent.com/40685592/45281884-df316e00-b4e1-11e8-9290-ed19c275a35a.png)
- [x] List of custom fields
![e76e1cbc_2018 10 09](https://user-images.githubusercontent.com/40685592/45282775-9b8c3380-b4e4-11e8-805b-b4eb0b5e900a.png)
- [ ] Edit button on hover
![985ef768_2018 10 09](https://user-images.githubusercontent.com/40685592/45298214-82997780-b510-11e8-875d-ae65920dc316.png)
 - [ ] Add a new field link
- [x] Done button
 
## Tasks
- [x] Remake using typescript (EditCard, CardField, BulkEditView, ) - 14
- [x] Add button svg and poopover - 1
- [x] Add condition to render custom filed list  - 1
- [x] Create layout and custom field card - 2
![29c31b42_2018 10 09](https://user-images.githubusercontent.com/40685592/45289681-7a344300-b4f6-11e8-8676-b37c41cebb65.png)
- [x] API for custom fields(add them to model, add tests) - 3
- [x] Get custom fields (from global state settings) - 2
- [x] add tests - 2
