### ISSUE TITLE
User can see settings page with "Customize fields" menu item and page (14/17.5)

### ISSUE THREAD

**Issue by denyskom** [softwareplanet/leadboard#201]
## Criteria
- [x] User can see settings page with menu on the left, after clicking on "Settings" button in navbar's dropdown
![8d0836ee_2018 10 09](https://user-images.githubusercontent.com/40685906/45283542-d8f1c080-b4e6-11e8-824f-1b48bb700b26.png)
- [x] User can choose customize fields menu item
- [x] User can see custom fields settings page 
![4abb4419_2018 10 09](https://user-images.githubusercontent.com/40685906/45283750-62a18e00-b4e7-11e8-843e-00747ff83850.png)
- [x] User can see tabs with (Leads, Organization, People)
- [x] User can see table with both default and custom fields depending on chosen tab
- [x] User can set "Show in details view" flag on custom fields in table
- [x] User can see modal window on clicking on add field button
![88a34292_2018 10 09](https://user-images.githubusercontent.com/40685906/45284705-d93f8b00-b4e9-11e8-9757-4f3c50c25f97.png)
- [x] User can add new custom field with default type text.
## Tasks
- [x] Create settings page with menu on the left - 1
- [x] Create menu item and "Customize data fields" page - 1
- [x] Add tabs and [table](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html) that shows default and custom fields depending on chosen tab - 4
With columns: 
      1. Field name. 
      2. Show in details view. 
      3. Type (optional since for now only one text type used 
- [x] Add button that allows to open modal window to add field (Text on button depends on chosen tab) -1
- [x] Create reusable component for modal window for adding custom field - 3
 (Has validation on blank field) 
![40038d63_2018 10 09](https://user-images.githubusercontent.com/40685906/45286138-b0b99000-b4ed-11e8-94b8-fad0ae9eb8cc.png)
- [x] Add modal window - 1
- [x] Add ability to change "Show in details view" flag - 1
- [x] Add tests - 2

**Comment by valentyntu** [comment]
Done in #214.
