### ISSUE TITLE
User can filter leads by owner (12)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#202]
## Criteria
- [ ] User can see owners tab in filter dropdown on leadboard
- [ ] User can see list of user in his domain in owners tab
- [ ] User can filter leads by owner on clicking on owner
- [ ] User can see all domain's leads by choosing everyone
![2f174076_2018 10 09](https://user-images.githubusercontent.com/40685314/45286036-66d0aa00-b4ed-11e8-81e7-dd00d2f88eb2.png)
## Tasks
- [ ] Add tabs to filters - 2
- [ ] Create backend to get all domain's users - 1.5
- [ ] Create actions and reducers to get all domain's users - 1
- [ ] Create backend to get all user's leads (and set it as default instead of all domain's) - 1.5
- [ ] Create actions and reducers for loading leads by owner - 1
- [ ] Change existing actions and reducers for loading all leads by domain - 1
- [ ] Add backend tests - 2
- [ ] Add frontend tests - 2
