### ISSUE TITLE
Custom funnels 11

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#203]
## Creteria
- [ ] User can see pipeline settings button on leadboard
![ce40373f_2018 10 09](https://user-images.githubusercontent.com/40685761/45287420-e9a73400-b4f0-11e8-8b86-42610fb841fb.png)
- [ ] User can see all pipelines on dropdown button pipelines
- [ ] User can change pipelines by click on some option in dropdown button pipelines
- [ ] User can see Pipeline settings page 
![a1fb07e7_2018 10 09](https://user-images.githubusercontent.com/40685761/45287956-33444e80-b4f2-11e8-9709-7acdafdd68b5.png)
- [ ] User can see change pipeLine on pipeline bar
![a1fb07e7_2018 10 09](https://user-images.githubusercontent.com/40685761/45288172-b5cd0e00-b4f2-11e8-8cee-71237797a238.png)
- [ ] User can see count of stages on pipeline tab
## Tasks
- [ ] Create pipeline button on leadboard 3
- [ ] Create pipeline page 8

**Comment by vladislavkoz** [comment]
duplicate:  https://github.com/softwareplanet/leadboard/issues/81
