### ISSUE TITLE
User can edit stage on customize funnel page (8/8.5)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#204]
## Criteria
- [x] User can see modal window on click stage's name
- [x] Modal window, that shown on click is equal to add stage, but already contains selected stage's info
![9d28f8cf_2018 10 09](https://user-images.githubusercontent.com/40685314/45289673-77d1e900-b4f6-11e8-9688-db34978badef.png)
- [x] User cannot save stage after setting empty name
- [x] User can update stage by choosing new name and clicking save
## Tasks
- [x] Extend modal from adding stage (add possibility to pass initial values via props) - 2/2
- [x] Create component that will use extended modal - 2/2
- [x] Add action and reducer for updating stage - 1/1.5
- [x] Create patch funnel backend - 2/1
- [x] Add tests - 1/1.5

**Comment by valentyntu** [comment]
Done in #216.
