### ISSUE TITLE
User can delete custom field on lead edit page (9)

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#205]
## Criteria
- [x] Delete button on hover
![045be022_2018 10 09](https://user-images.githubusercontent.com/40685592/45298283-b70d3380-b510-11e8-9fa6-c3868b611b47.png)
- Delete button on edit
![6da90c0f_2018 10 09](https://user-images.githubusercontent.com/40685592/45298357-ecb21c80-b510-11e8-8656-77c36152f892.png)
- [x] Delete button confirmation 
![f8d7b348_2018 10 09](https://user-images.githubusercontent.com/40685592/45283639-15252100-b4e7-11e8-84fc-64af761ad310.png)

## Tasks

- [x] API delete custom field from domain with test - 4
- [x] Svg and delete functionality - 3
- [x] add test - 2

**Comment by valentyntu** [comment]
Done in #213.
