### ISSUE TITLE
User can see main info about contact (5/1.5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#217]
## Criteria
- [x] User can see contact name
- [x] User can see contact owner (created by)
- [x] Contact icon to the left of name
## Tasks
- [x] Add header component with styles (2/1)
- [x] Find contact icon (1/0.5)
