### ISSUE TITLE
User can see general information about organization (5/2.5)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#218]
## Criteria
- [x] User can see general information about organization
- [x] User can see organization page
## Tasks
- [x] Create reducers for organization page (1/1)
- [x] Create general information block like this (3/1.5) 
![image](https://user-images.githubusercontent.com/40685761/45609270-ddc2f100-ba5f-11e8-82c4-88a8a9614ec1.png)
- [x] Tests (1h)
