### ISSUE TITLE
User can see organization's details (6)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#220]
## Criteria
- [x] User can see details about organization 
- [x] User can see customFields for organization
## Tasks
- [x] Reuse componenent from edit lead (2h)
![image](https://user-images.githubusercontent.com/40685761/45609665-87ef4880-ba61-11e8-8ab3-10478874cd0e.png)
- [x] Reuse component for custom Fields from edit lead (2h) 
- [ ] Tests (1h)

**Comment by valentyntu** [comment]
Done in #285
