### ISSUE TITLE
User can see all people for organization (8/12.5)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#223]
## Criteria
- [x] User can see all people for organization
- [x] User can go to contact page by click on contact on people card
## Tasks
- [x] Create people  card (2h) 
- [x] Show this message if no people for organization (0.5h)
![image](https://user-images.githubusercontent.com/40685761/45609896-8f632180-ba62-11e8-942c-b971d7eb3f7b.png)
- [x] Add optional render for people card (0.5h)
- [x] Show all users for organization if exists (2h)
![image](https://user-images.githubusercontent.com/40685761/45609973-e9fc7d80-ba62-11e8-9676-aa6d10b0cb7d.png)
- [x] Tests (1h)
- [x] Add backend for getting alll contacts related to specific organization (2h)

**Comment by valentyntu** [comment]
Done in #268
