### ISSUE TITLE
User can customize contact's custom fields in details card (8)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#224]
## Criteria
- [x] "Customize fields" button
- [x] Default custom fields after click
- [x] Adding new field after click on "add new field" label
## Tasks
- [x] Reuse adding new custom fields on lead's page (5)
- [x] Add tests (3)

**Comment by valentyntu** [comment]
Done in #279
