### ISSUE TITLE
User can see contact's notes history (4.5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#225]
## Criteria
- [ ] notes history as cards
- [ ] time (created at)
- [ ] owner (created by)
## Tasks
- [ ] reuse notes history (3)
- [ ] add tests (1.5)
