### ISSUE TITLE
User can see all open! organization's leads on organization page 6

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#226]
## Criteria 
- [ ] User can see all open! leads on leads card
- [ ] User can go on lead page by click on lead  card
## Tasks
- [ ] Create leads card (2h)
![image](https://user-images.githubusercontent.com/40685761/45610464-a99dff00-ba64-11e8-90bf-82558548b952.png)
- [ ] Create lead card (2h)
![image](https://user-images.githubusercontent.com/40685761/45611132-fda9e300-ba66-11e8-9a63-6c4418632df5.png)
- [ ] Tests (1h)
