### ISSUE TITLE
Extract note as new model in DB schema (8)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#227]
## Tasks
- [x] create new db model (0.5)
- [x] fix API request handlers (2)
- [x] fix tests (1)
- [x] add notes to contact, organization and lead (1)
- [x] create db migration script (2) 
- [x] fix FE actions with new routes (1)
