### ISSUE TITLE
User can see the list of connected activities on contact's page (8)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#228]
## Criteria
- [ ] User can see the list of all activities connected with him/her
![73b7fd95_2018 17 09](https://user-images.githubusercontent.com/40685314/45611023-b58ac080-ba66-11e8-8580-5b1e2af09bdb.png)
## Tasks
- [ ] Reuse component from edit lead page - 4 
- [ ] Add backend for loading activities by user - 2
- [ ] Add backend tests - 1
- [ ] Add action,reducer to search for activities by contact id (frontend) - 1
