### ISSUE TITLE
User can add note for organization 6

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#229]
## Criteria
- [x] User can see add notes editor 
- [x] User can add new note 
## Tasks
- [x] Create actions, reducers (1h)
- [x] Create rest api for add new notes (1h) 
- [x] Reuse add new notes component from edit lead (3h)
![image](https://user-images.githubusercontent.com/40685761/45611619-b1f83900-ba68-11e8-9556-0fca7d3f11c8.png)
- [x] Tests
