### ISSUE TITLE
User can add activity for organization 6

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#230]
## Criteria
- [x] User can see add new activity panel 
- [x] User can add new activity 
## Tasks
- [x] Create actions reducers (2h)
- [x] Reuse component from edit lead (2h)
![image](https://user-images.githubusercontent.com/40685761/45612035-4e6f0b00-ba6a-11e8-9da2-f551da886718.png)
- [x] Tests
