### ISSUE TITLE
User can add new note to contact (4.5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#231]
## Criteria
- [x] user can see editor
- [x] add note to displayed after save
- [x] don't save empty note
## Tasks
- [x] reuse note editor component (3)
- [x] add tests (1.5)
