### ISSUE TITLE
User can see all notes for organization 9

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#232]
## Criteria
- [ ] User can see all notes for organization
![image](https://user-images.githubusercontent.com/40685761/45612376-77dc6680-ba6b-11e8-91f5-dce38725a54e.png)
## Tasks
- [ ] Create reusable history for models History (4.5h)
- [ ] Use Notes component (1.5h)
- [ ] Create actions reducers (2h) 
- [ ] Tests (1h)
