### ISSUE TITLE
User can see all activities for organization 7

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#233]
## Criteria
- [ ] User can see all activities for organization 
## Tasks 
- [ ] Use activities component from edit lead (3h)
![image](https://user-images.githubusercontent.com/40685761/45612577-11a41380-ba6c-11e8-972f-e17c993fb634.png)
- [ ] Add actions/reducers (2h)
- [ ] Tests (1h)
