### ISSUE TITLE
User can add activity to contact on the contact's page (6)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#234]
## Criteria
- [x] User can see tabs with "Add activity" tab
![3139e742_2018 17 09](https://user-images.githubusercontent.com/40685314/45612125-a86fd080-ba6a-11e8-8b73-87dfe1fb58c7.png)
- [x] User will see add activity view after clicking on  "Add activity" tab
![dbcb8eba_2018 17 09](https://user-images.githubusercontent.com/40685314/45612354-6bf0a480-ba6b-11e8-9e1c-5a9f06386ef6.png)
## Tasks
- [x] Reuse add activity component - 2
- [x] Add/adjust actions and reducers for adding activity to contact - 2
- [x] Test everything - 2
