### ISSUE TITLE
User can change lead's pipeline with stage (10)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#236]
## Criteria
- [x] doent displaying if only 1 pipeline exists
- [x] user can select pipeline in dropdown
- [x] only selected pipeline's stages
## Tasks
- [x] optional rendering in header (1)
- [x] add popover with pipeline selection (4)
- [x] add redux flow (2)
- [ ] add tests (3)

**Comment by valentyntu** [comment]
Done in #248
