### ISSUE TITLE
User can switch  pipelines on dashboard (8)

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#237]
## Criteria 
- [x] Only one pipeline should have settings button near filter button 
![image](https://user-images.githubusercontent.com/40685592/45612964-58463d80-ba6d-11e8-9278-035b6456d6a1.png)
- [x] More than one pipeline dashboard has Pipeline button 
![image](https://user-images.githubusercontent.com/40685592/45613007-8461be80-ba6d-11e8-97a6-2d050d25ec61.png)
- [x] Click on the Pipeline button should trigger a dropdown where to chose pipeline 
![image](https://user-images.githubusercontent.com/40685592/45613128-f76b3500-ba6d-11e8-9fa8-2b8d8ab09664.png)
- [x] Last item should always be pipeline settings

## Task
- [ ] Add frontend tests - (2)
- [x] Make buttons layout - (2)
- [x] Check icon on current pipeline - (1)
- [x] Add drop down to button (reuse from navbar) - (2)   
- [x] Get drop down menu items(pipelines) from props - (1)

**Comment by valentyntu** [comment]
Done in #255
