### ISSUE TITLE
User can delete lead (5.5/6)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#238]
## Criteria
- [x] User can see "..." button in the top right corner of the edit lead page
![f454066e_2018 17 09](https://user-images.githubusercontent.com/40685314/45612974-609e7880-ba6d-11e8-8559-465694a49501.png)
- [x] On clicking "..." button user sees a popover with item "Delete"
![e490e12f_2018 17 09](https://user-images.githubusercontent.com/40685314/45613019-8cb9f980-ba6d-11e8-91b4-e0a3aef1c9b3.png)
- [x] On choosing "Delete" user will see a confirmation dialogue
![3b6b5b5a_2018 17 09](https://user-images.githubusercontent.com/40685314/45613056-b3783000-ba6d-11e8-8eb1-e6a7ed993eaf.png)
## Tasks
- [x] Add "..." button with popover to edit lead page - 1
- [x] Make button to trigger popover - 0.5
- [x] Add item "Delete" to popover - 0.5
- [x] Add click handler for "Delete" item - 0.5
- [x] Create backend for deleting lead - 1
- [x] Create action and reducer for deleting lead - 2

**Comment by valentyntu** [comment]
Done in #241.
