### ISSUE TITLE
User can see lead's stage age.

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#25]
## Criteria
- [ ] Duration in days inside passed stages
- [ ] Duration on hover
- [ ] If duration <1 day, on hover show duration in minutes
## Tasks
- [ ] Add change log field to Lead model
- [ ] Count each lead's stage age
