### ISSUE TITLE
User can see organization page with basic layout (2/2)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#252]
## Tasks
- [x] Create organization page (0.5/0.5)
- [x] Create basic layout components (1/1)
- [x] Connect root component to redux (0.5/0.5)
