### ISSUE TITLE
User can Log out from his own account

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#26]
## Criteria
- [x] User can see logout button on all pages
- [x] User must log out automatically if has delays token

## Tasks
- [x] Create log out button - 0.5h
- [x] Remove token on Log out 0.5h
- [x] Redirect user on Login page after logout 0.5h
- [x] Log out user if he has expired token 0.5h
- [x] Add test 2h
