### ISSUE TITLE
Lead autocomplete on add activity tab

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#264]
## Criteria 
- [x] Lead auto complete input 
![image](https://user-images.githubusercontent.com/40685592/46016185-c679a880-c0dc-11e8-8e21-93a68bb163dc.png)
- [x] should have x on the right to clear input
- [x] should clear on esc button
- [x] should blur on esc if value is empty

## Tasks
- [x] make component(similar to organization and contact autocomplete)
- [x] add backend 
- [x] use it on add activity
