### ISSUE TITLE
User can edit organization name on organization detailed view (2/1.5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#265]
## Criteria
- [x] popover opens after click on name
- [x] name changes after save
- [x] yellow background after hover on name
## Tasks
- [x] add update action for organization  (1/1)
- [x] reuse popover component (1/0.5)
