### ISSUE TITLE
User can edit contact's name on contact detailed page (2/1.5)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#266]
## Criteria
- [x] popover opens after click on name
- [x] name changes after save
- [x] yellow background after hover on name
## Tasks
- [x] add update action for contact (1/0.5)
- [x] reuse popover component (1/1)
