### ISSUE TITLE
Browser's "Back" and "Forward" buttons don't work for pipeline switch on dashboard

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#269]
## Criteria 
- [ ] if  pipeline was changed, back button change pipeline to previous on dashboard
- [ ] if  pipeline was changed, next button change pipeline to next on dashboard 
## Tasks 
- [ ] add setActiveFunnel action when change url with back forward browser's buttons 
- [ ] load dashboard on change url
