### ISSUE TITLE
Fix code review issues

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#27]
Fix issues of pull request #9

## Tasks
- [x] add backend test for creation default funnel and stages
- [x] remove empty AddLead.afterOpenModal()
- [x] fix order setting when creating lead
