### ISSUE TITLE
User can add new note to lead (7)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#28]
## Criteria
- [x] User can type note in text area
- [x] User can save changes
- [x] User can cancel changes
- [x] Buttons should be over text area
## Tasks 
- [x] Create tabs component with styles (4)
- [x] Create buttons over text area (2)
- [x] Create rest API for adding new note (1)
- [x] Create test (1)
