### ISSUE TITLE
User can see all notes for lead (9)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#29]
## Criteria
- [x] User can see notes for lead on edit page 
- [x] User can see author of note
- [x] User can see date of making a note 
## Tasks
- [x] Create react component Note() 1.5h
- [x] Make styles 2.5h
- [x] Put note data in store on opening edit page 1h
- [x] Create rest API for getting note data 1h
- [x] Create notes mapping from store 1h
- [x] Create test 2h
