### ISSUE TITLE
User can add a new lead to the leadboard

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#3]
## Criteria
- [x] new lead appears in the leadboard after clicking save
- [x] must enter contact name or organization 

## Tasks
- [x] make component's layout
- [x] fix submit hander
- [x] add client-side validation
- [x] fix styles & make styles' names conventional
- [x] add tests
