### ISSUE TITLE
User can get notification about activity on email

### ISSUE THREAD

**Issue by denyskom** [softwareplanet/leadboard#30]
## Criteria
- [ ] User should receive notification the day before activity
- [ ] User should receive notification 30 minutes before activity   
## Tasks
- [ ] Add delivery manager (mailgun for example)
- [ ] Add scheduler that will run mailing method
- [ ] Query all activities and user they assigned to (get activity, and user email)
- [ ] Form massage based on activity and add delivery time to it
- [ ] Send information to delivery manager
