### ISSUE TITLE
User can edit note for lead (7/10)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#31]
## Criteria
- [x] User can see 'spred icon' button on note card

- [x] User can see edit button on click  in 'spred icon'  button 

- [x] User can see text editor with current note, after click on edit button
- [x] User can save the changes in the note
- [x] User can see who did last note update  
## Tasks
- [x] Create 'spred icon' button  on note card (0.5/0.5)
![65185a38_2018 27 08](https://user-images.githubusercontent.com/40685761/44659938-9f14ba80-aa0e-11e8-97c4-aadc8850d3f4.png)
- [x] Create edit button on 'spred icon' button (1/1)
![21796b63_2018 27 08](https://user-images.githubusercontent.com/40685761/44660033-fca90700-aa0e-11e8-90ba-ab130411b8e1.png)
- [x] Add optional render for note card(add edit mode) (1)
![b4c425f4_2018 27 08](https://user-images.githubusercontent.com/40685761/44660455-49d9a880-aa10-11e8-9a51-def0a2d07885.png)
- [x] Create rest API for updating note (1/1.5)
- [x] Add last updater (1.5/1)
- [x] Create test (1.5/2.5)
