### ISSUE TITLE
User can delete note for lead (5/1.5)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#32]
## Criteria 
- [x] User can see "Delete" button after click  "spread icon" button on note card
- [x] User can see confirmation message on clicking delete button

## Tasks 
- [x] Add delete button in 'spred icon' button on note card (1/0.3)
![13c4d0a0_2018 27 08](https://user-images.githubusercontent.com/40685906/44660121-53164580-aa0f-11e8-8231-e0719f0594e9.png)
- [x] Create confirmation message for delete (0.5/0.5)
![6c5eb06e_2018 27 08](https://user-images.githubusercontent.com/40685906/44660328-f5cec400-aa0f-11e8-859f-6779126d0d2c.png)
- [x] Create rest API for deleting note (2/0.5)
- [x] Create test (1.5/0)
