### ISSUE TITLE
User can see detailed lead's organization information

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#33]
## Criteria
- [x] Should be as card on side panel
- [x] Near the organization name rounded organization icon
- [x] Must be shown address field
- [x] If field is empty show only placeholder
## Tasks
- [x] Create reusable card component for person and organization (6)
