### ISSUE TITLE
User can pin - unpin note for lead

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#34]
## Criteria
- [ ] User can see pin button on 'spred icon'  button on note card
- [ ] User can see pined note above the text editor for adding new note
## Tasks 
- [ ] Add pin button on 'spred icon' button on note card
- [ ] Create optional render for 'spred button' on pinned note wich include (Edit, Unpin, Delete buttons)
- [ ] Create react component pinned note with 'spred button' wich include (Edit and Unpin button) 
- [ ] Create marking note as pinned and add it to pinned in store, after click on pin button
- [ ] Create rest API for editing note status
- [ ] Create mapping pinned notes from store
- [ ] Create marking note as unpinned and remove it from pinned in store, after click on unpin button
