### ISSUE TITLE
User can edit lead's organization (10)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#35]
## Criteria
- [x] User can press pencil icon in card header for edit current fields
- [x] After click on pencil button card content replaces by form with name and address fields
- [x] If data already exists, it must be entered in field
- [x] If data already exists, near the field must be pencil button for editing only this field
- [x] If data empty, near the field must be clickable '+ Add value' label
- [x] Near the organization name must be Rename button which works same as pencil button

## Tasks
- [x] Add pencil icon button in card header for edit current fields 0.5h
- [x] Create optional render for card ( Edit mode ) 3h
- [x] Create optional render for fields( render data or clickable '+ Add value' label ) 0.5h
- [x] Add rename button for organization name 1h
- [x] Create rest API for updating organization fields 2h
- [x] Add actions and reducers to load and update organization - 1h
- [x] Create tests 2h
