### ISSUE TITLE
User can edit lead's person information (9)

### ISSUE THREAD

**Issue by NazarPo** [softwareplanet/leadboard#36]
## Criteria
- [ ] User can press a pencil icon in card header to edit current fields
- [ ] After click on a pencil button card content replaces by form with name, phone and email fields
- [ ] If data already exists, it must be displayed in field
- [ ] If data already exists, near the field must be a pencil button for editing only this field
- [ ] If data empty, near the field must be a clickable '+ Add value' label
- [ ] Near the person name must be Rename button which give a possibility for user to change person name

## Tasks
- [ ] Add pencil icon button in card header for edit current fields 0.5h
- [ ] Create optional render for card ( Edit mode ) 3h
- [ ] Create optional render for fields( render data or clickable '+ Add value' label ) 0.5h
- [ ] Add rename button for organization name 1h
- [ ] Create rest API for updating organization fields 2h
- [ ] Create tests 2h

**Comment by valentyntu** [comment]
Duplicates #73
