### ISSUE TITLE
User can assign co-workers to this activity

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#37]
## Criteria
- [ ] user can assign co-workers to activity when creating
- [ ] user can see suggestions when typing name

## Tasks
- [ ] use component from #19
- [ ] add new field to adding activity form
- [ ] make tests
