### ISSUE TITLE
User can choose a target when creating action

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#38]
## Criteria
- [ ] user can choose contact or company when creating action
- [ ] user receives suggestions when typing

## Tasks
- [ ] reuse component from #19
- [ ] add tests
