### ISSUE TITLE
User can log in with Google account

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#39]
## Criteria
- [ ] User can see log in by google account button on login page
- [ ] User can log in with google account

## Tasks 
- [ ] Create log in with google account
