### ISSUE TITLE
User can see leadboard after login

### ISSUE THREAD

**Issue by NazarPo** [softwareplanet/leadboard#4]
## Criteria
- [x] funnel is loaded from DB 1h
- [x] stages are loaded from DB 1h
- [x] see lead placeholders if user doesn't have any leads: first stage = number of stages. last stage equals one 2h
- [x] in stage headers user can see count of stage's leads 1h

## Test
- [x] check leadboard's actions on dispatching 0.5h
- [x] render the connected leadboard component 0.5h
- [x] check props mathes with initialState 0.5h
- [x] should handle load leadboard, leads, stages actions 0.5h
