### ISSUE TITLE
User can sign in with google account

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#40]
## Criteria 
- [ ] User can see sign in with google account on registration page
- [ ] User can sign in with google account 
## Tasks
- [ ] Create Sign in with google account
