### ISSUE TITLE
User can see warning icon on lead where no activities are planned (5)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#44]
## Criteria
- [ ] when new lead is added to leadboard a warning icon appears on it
![warning icon](https://user-images.githubusercontent.com/40685314/44153250-644e7bf0-a0b0-11e8-9d0a-3e3ed14df9f3.png)
- [ ] if an activity is added an icon changes to following
![arrow icon](https://user-images.githubusercontent.com/40685314/44153528-1f813caa-a0b1-11e8-9704-29f50acddbde.png)
- [ ] when all activities are done the warning icon also appears

## Tasks
- [ ] find suitable icons - 1h
- [ ] extend lead layout with icon placeholder - 1h
- [ ] create function that checks if lead has planned activities - 1h
- [ ] add icon rendering on the lead that depends on checking function - 0.5h
- [ ] add tests - 1.5h

**Comment by yaroslavmo** [comment]
Close due to dublicate
