### ISSUE TITLE
Deploy staging to heroku

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#48]
## Tasks
- [x] create and connect m-lab DB
- [x] get db url from env variables
- [x] if env variables exist, get static views from frontend build
- [x] create heroku account
- [x] set env variables on heroku
