### ISSUE TITLE
User can see detailed lead's contact person information (6)

### ISSUE THREAD

**Issue by VladyslavTy** [softwareplanet/leadboard#6]
## Criteria
- [x] Should be as card on side panel
- [x] Near the contact name rounded person icon
- [x] Must be shown phone, email fields
- [x] If field is empty show only placeholder
## Tasks
- [x] Create reusable card component for person and organization (6)
