### ISSUE TITLE
User can see a hint of names after entered contact name in add lead modal

### ISSUE THREAD

**Issue by NazarPo** [softwareplanet/leadboard#64]
## Criteria
- [x] each time user entered a new symbol he can see a hint of contacts names if those exists
- [x] if there no coincidence user can see a hint with message that it will be new contact
- [x] if user entered one symbol hints don't appear
- [x] if entered name is new user can see a label "NEW"
- [x] if user select contact from list of hints and this contact has organization, organization input will be changed to organization name

## Tasks 
- [x] add rendering unordered list of hints 1h
- [x] add api request handler for GET contact 0.5h
- [x] add label with message "NEW" 0.5h
- [x] add capability of choosing contact name from list of hints 2h
- [x] create tests 2h

## Tests
_todo_
