### ISSUE TITLE
User can see all his leads on the leadboard

### ISSUE THREAD

**Issue by denyskom** [softwareplanet/leadboard#7]
## Criteria
- [x] User lead contains avatar, deal name and current person name
- [x] If contact person is absent lead should display organization name
- [x] After user's click link shoud route to it's edit panel
- [x] Lead link should contain funnel id and link id in params
**Backend endpoint**:
- [x] User can create lead with  person
- [x] User can create lead with  organization
- [x] User can create lead with  person and organization
## Tasks 
- [x] Create react component Lead
- [x] Add ability to create new person 
- [x] Add ability to create new person with organization
- [x] Populate all information to state
