### ISSUE TITLE
User can edit lead's contact information (4)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#73]
## Criteria
- [x] When user changes any field in edit mode and clicks on save, person's information is updated
##Tasks
- [x] Make backend for updating person (1)
- [x] Make backend tests (0.5)
- [x] Add action and reducer for updating organization (1)
- [x] Add action calls and checks to contact card's components (1)
- [x] Add frontend tests (0.5)
