### ISSUE TITLE
Create tabs component for edit lead's actions

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#74]
##Tasks
- [ ] create tabs component
- [ ] create header with icons for activity and notes
- [ ] add styles to tabs component
