### ISSUE TITLE
User can see filter panel for lead information on edit page (4.5)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#75]
## Criteria
- [x] User can see filter panel
- [x] User can choose some filter option (notes, activities)
- [x] User can see different lead info on click some filter option
## Tasks 
- [x] Add filter panel on edit page 2h
![770cdf2d_2018 22 08](https://user-images.githubusercontent.com/40685761/44470274-efb49e00-a631-11e8-8d9d-3a419eab8265.png)
