### ISSUE TITLE
User must register company with unique name

### ISSUE THREAD

**Issue by NazarPo** [softwareplanet/leadboard#8]
## Criteria
- [ ] system accepts only unique company name
- [ ] user see error if company name is already taken

## Tasks 
- [ ] create css styles for register component
- [ ] add unique name validator
- [ ] _do further breakdown_
