### ISSUE TITLE
User can go to pipeline settings page (9)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#81]
## Criteria
- [x] User can see this button on toolbar after login
![649f1c61_2018 27 08](https://user-images.githubusercontent.com/40685314/44645519-8beaf600-a9e0-11e8-8b4d-d256650d5613.png)
- [x] User can see list of all pipelines after click on pipeline settings button
- [x] User can switch pipelines by pipelines bar
![a1fb07e7_2018 10 09](https://user-images.githubusercontent.com/40685761/45288172-b5cd0e00-b4f2-11e8-8cee-71237797a238.png)  
- [x] User can go to pipeline settings page by clicking button "Pipeline settings"
- [x] User can see all stages of current pipeline on settings page
![86db5a4b_2018 27 08](https://user-images.githubusercontent.com/40685314/44645689-2e0ade00-a9e1-11e8-8207-3e0b14e764f2.png)

## Tasks
- [x] Create button with suitable styles (1)
- [x] Create conditional render for pipelines on pipelines button (1)
- [x] Create protected route for settings page (0.5)
- [x] Make pipeline settings page layout (3)
- [x] Make pipeline stages view (4)
- [x] Add loading pipelines from store (0.5) 
- [x] Add tests (2)
