### ISSUE TITLE
User can edit current pipeline's name (5)

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#82]
## Criteria
- [x] User can see "Edit" button near pipeline header on pipeline settings page
![16b3e255_2018 27 08](https://user-images.githubusercontent.com/40685314/44646764-b63eb280-a9e4-11e8-9723-351019730719.png)
- [x] User can edit pipeline name in modal window that appears on click "Edit"
![e8f851e2_2018 27 08](https://user-images.githubusercontent.com/40685314/44646857-09b10080-a9e5-11e8-84c6-1a466fad533e.png)
- [ ] In modal "enter" works as save and "esc" as  cancel

## Tasks
- [x] Create backend route for updating pipeline (1)
- [x] Create actions and reducers for updating pipeline (1)
- [x] Add default button "Edit" to pipeline view (0.5)
- [x] Create modal that appears on click "Edit" button (1.5)
- [x] Add tests (1)
