### ISSUE TITLE
User can reopen closed lead (8/5)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#83]
## Criteria
- [x] User can see reopen button on edit lead page if lead marked as won or lost 
- [x] User can reopen lead after set it as won or lost by clicking on reopen button on edit page
## Tasks 
- [x]  Create optional render for lead (lead status panel) (2/1.5)
![a7430339_2018 27 08](https://user-images.githubusercontent.com/40685761/44647217-1c780500-a9e6-11e8-9598-313d3adaff15.png)
- [x] Add reopen button on edit lead page (2/1.5)
![c42d843e_2018 27 08](https://user-images.githubusercontent.com/40685761/44647429-bb046600-a9e6-11e8-8c65-bd7da43acb6c.png)
- [x] Create action&reducer (1/0)
- [x] Create rest API (1.5/0)
- [x] Tests (2)
