### ISSUE TITLE
User can add stages to funnel 8

### ISSUE THREAD

**Issue by valentyntu** [softwareplanet/leadboard#84]
## Criteria
- [ ] User can see add stage to funnel button 
![9fadb956_2018 10 09](https://user-images.githubusercontent.com/40685761/45289845-cf705480-b4f6-11e8-891d-a56aed4e528e.png)
- [ ] User can see modal window after click on add stage button
![95d2628f_2018 10 09](https://user-images.githubusercontent.com/40685761/45289956-0e060f00-b4f7-11e8-9423-51be0599bdbf.png)
## Tasks
- [ ] Create add stage button 1
- [ ] Create modal window 3
- [ ] Create rest api for add new stage 1
- [ ] tests 2
