### ISSUE TITLE
User can see label with status indicator if lead is won or lost (4/1)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#90]
## Criteria
- [x] User can see Won label if lead marked as won
- [x] User can see Lost label if lead marked as loose
## Tasks
- [x] Add status label on edit lead page (1)
![c42d843e_2018 27 08](https://user-images.githubusercontent.com/40685761/44648319-55fe3f80-a9e9-11e8-8d77-4dac42abb91e.png)
- [x] Create optional render for status label (1)
won label - 
![69d60009_2018 27 08](https://user-images.githubusercontent.com/40685761/44645534-9d340280-a9e0-11e8-936b-b527dc230871.png)
lost label - 
![4fc5fefa_2018 27 08](https://user-images.githubusercontent.com/40685761/44646509-e6d21c80-a9e3-11e8-9c11-d7fd3b39a03d.png)
- [x] Create tests (1)
