### ISSUE TITLE
User can see modal window after click on lose button  (8)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#92]
## Criteria
- [ ] User can see lose reason and comments(optional) on modal widow
- [ ] User can see modal window after click on lose button with lose reason and comments (optional) 
- [ ] Validation on lost lead reason (cannot be empty)
## Tasks
- [ ] Create modal with lose reason and optional comments(3)
![de6d067c_2018 27 08](https://user-images.githubusercontent.com/40685761/44645493-7249ae80-a9e0-11e8-9625-eeee99193ad4.png)
- [ ] Add validation on loose lead modal (2)
![ac271959_2018 27 08](https://user-images.githubusercontent.com/40685761/44645591-cfddfb00-a9e0-11e8-994b-dd201e31b800.png)
- [ ] Create tests (1.5)
- [ ] Code review (1.5)
