### ISSUE TITLE
User can see all lead's activities (15)

### ISSUE THREAD

**Issue by SamardakOleh** [softwareplanet/leadboard#93]
## Criteria
- [x] User can see planned activities for lead on edit page
![image](https://user-images.githubusercontent.com/40685592/44660726-3713a380-aa11-11e8-83ff-f0607a318ebc.png)

- [x] Planned activities placed on a time line bar
![image](https://user-images.githubusercontent.com/40685592/44661580-ba35f900-aa13-11e8-9bd6-950ce54a490c.png)

- [x] User can see time of activity (red if expired)
![image](https://user-images.githubusercontent.com/40685592/44662193-b014fa00-aa15-11e8-92d4-131248f466ee.png)

- [x] User can see time of activity (grey if passed or planned)
![image](https://user-images.githubusercontent.com/40685592/44662211-c02cd980-aa15-11e8-8f36-762984203fa3.png)

- [x] User can see time of activity (green today if time is not specified)
![image](https://user-images.githubusercontent.com/40685592/44662266-f36f6880-aa15-11e8-8abc-67cbf2120f62.png)

## Tasks
- [x] Create activity component 4h
- [x] Make styles 1h
- [x] Put activity data in store on opening edit page(reducer, action) 1h
- [x] Create rest API for getting activity data 1h
- [x] Create activities mapping from store 1h
- [ ] Add tests - 3h
- [x] Change activity status (planned, past) 2h
