### ISSUE TITLE
User can see all organisations (16)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#98]
## Criteria
- [x] User can see contacts dropdown on leadbord (Organisations option)
- [x] User can see table with all organisations on organisations page
- [x] Table with organizations has the following styles
![68e33c2e_2018 17 09](https://user-images.githubusercontent.com/40685314/45609285-fcc18300-ba5f-11e8-8412-c7c9d7051c12.png)
- [x] User can see total amount of organizations at top of the page just below the navbar
![247162af_2018 17 09](https://user-images.githubusercontent.com/40685314/45609508-fbdd2100-ba60-11e8-86d8-69b4caa4da1e.png)
- [x] User can see info from custom fields for organizations in the table
- [x] User can see amount of people connected with this organization
- [x] User can see amount of open and closed leads, owner and next activity date
## Tasks
- [x] Add new item "Organizations" to dropdown on navbar - 1
- [x] Reuse/make reusable component from contacts page - 4
- [x] Make table display all the required data from props - 2
- [ ] Add client tests - 2
- [x] Add backend for getting all aggregated data about organizations - 4
- [ ] Add backend tests - 2
- [x] Add action and reducer - 0.5
- [x] Make table display loaded data from db - 0.5

**Comment by valentyntu** [comment]
Done in #185.
