### ISSUE TITLE
User can add new organization on organizations page (11)

### ISSUE THREAD

**Issue by vladislavkoz** [softwareplanet/leadboard#99]
## Criteria
- [x] User can see "Add organization"| button on organisations page
![abef6462_2018 17 09](https://user-images.githubusercontent.com/40685314/45609870-735f8000-ba62-11e8-9bc7-5a9cb504f848.png)
- [x] On clicking "Add organization"| button user will see modal window like the following
![edb2b92e_2018 17 09](https://user-images.githubusercontent.com/40685314/45609922-b3befe00-ba62-11e8-82a4-018a44afbacc.png)
- [x] User can type organization's name and press "Save", after that new organization will be added to table.
- [x] Organization's name cannot be empty, user will see red border validation on name input after first attempt to send empty name.
![5cf5d883_2018 17 09](https://user-images.githubusercontent.com/40685314/45610007-10bab400-ba63-11e8-9d91-9580108f1170.png)
## Tasks
- [x] Add button to organizations' page - 0.5
- [x] Add modal for creating organization (the easiest way is to move modal to the same component as button like addLead) - 4
- [x] Add name validation - 0.5
- [x] Create backend for adding organization - 2
- [x] Add backend tests - 1
- [x] Add action/reducer for creating organization - 1
- [x] Add frontend tests - 2

**Comment by valentyntu** [comment]
Done in #246.
